name: Docker Images

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Cache target
        uses: actions/cache@v4
        with:
          path: |
            target/
          key: ${{ runner.os }}-release-${{ hashFiles('Cargo.lock') }}

      - name: Get nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build binary
        uses: ronnychevalier/cargo-multivers@main
        with:
          out_dir: binaries/

      - name: Move binary
        run: |
          mv binaries/bsky-jet-stream bsky-jet-stream

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/bsky-jet-stream

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
